// AutolinkedNativeModules.g.cpp contents generated by "react-native autolink-windows"
// clang-format off
#include "pch.h"
#include "AutolinkedNativeModules.g.h"

// Includes from @op-engineering/op-sqlite
#include <winrt/OpEngineeringOpSqlite.h>

namespace winrt::Microsoft::ReactNative
{

void RegisterAutolinkedNativeModulePackages(winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::ReactNative::IReactPackageProvider> const& packageProviders)
{ 
    // IReactPackageProviders from @op-engineering/op-sqlite
    packageProviders.Append(winrt::OpEngineeringOpSqlite::ReactPackageProvider());
}

}
